server:
  port: 8000


spring:
  session:
    store-type: redis #将session保存到redis中
    redis:
      database: 1 #redis 默认0-15总共16个库 这里采用1库
      host: 127.0.0.1  #到docker后修改，还要加上用户名和密码，且redis中配置访问的主机的ip，以提高安全性
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 5
          min-idle: 0
      port: 6379
      timeout: 5000
  cloud:
    sentinel: #sentinel配置
      web-context-unify: false #关闭context整合
      transport:
        port: 8719                  #跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: localhost:9999   #dashboard地址与端口
      eager: true
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: resorder


logging:
  level:
    root: info
    org.springframework.web.client: debug
    org.apache: error
    com.yc.api: DEBUG
  file:
    #    name: mylog.log
    path: logs/


feign:
  compression:
    request:
      mime-types: #可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 #超过2048字节进行压缩
      enabled: true
    response:
      enabled: true
