server:
  port: 8000


spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: resorder


logging:
  level:
    root: info
    org.springframework.web.client: debug
    org.apache: error
    com.yc.api: DEBUG
  file:
    #    name: mylog.log
    path: logs/


feign:
  compression:
    request:
      mime-types: #可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 #超过2048字节进行压缩
    response:
      enabled: true
