server:
  port: 20001

spring:
  application:
    name: res-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
#        namespace: res134

    gateway: #基础的路由转发配置
      routes: #查看配置源码  routes是一个有序的list集合
        - id: res-good   #唯 一区别的名字
#          uri: http://localhost:9200   #http://localhost:9200/resfood/findById/1
          uri: lb://resfood #resfood服务名 -> 利用loadBalancer保存的服务列表选一台服务器  （gateway与resfood服务在同一个命名空间下）
          predicates:
            - Path=/resfood/**  #http://localhost:20001/resfood/findById/1
        - id: baidu   #唯 一区别的名字
          uri: http://www.baidu.com    #都转发到baidu  替换请求路径http://localhost:20001/ xx
          predicates:
            - Path=/**  #所有请求（通用配置）

management:                                #通过 actuator暴露此服务的管理端口
  endpoints:
    web:                                   #通过web来暴露管理API,
      exposure:
        include: "*"                      #  * 代表将所有的端口暴露   一定要加"",因为 *是特殊字符，加""防止转义